// const BASEURL = 'http://175.41.176.135:3000/v1/';
const BASEURL = 'http://api.mycommunity.qa/v1/';

export const API = {
  baseUrl: BASEURL,
  fileUpload: 'http://api.earnbylearn.online/ebyl/fileupload',
  userFeeds: BASEURL + 'user-feeds',
  productList: BASEURL + 'products',
  individualUser: BASEURL + 'users/register/individual',
  corporateUser: BASEURL + 'users/register/corporate',
  industryTypes: BASEURL + 'industry-types',
  businessCategory: BASEURL + 'business/category',
  businessSubCategory: BASEURL + 'business/sub-category/',
  login: BASEURL + 'users/login',
  logout: BASEURL + 'users/logout',
  resendOTP: BASEURL + 'users/verify/resend-token',
  verifyUser: BASEURL + 'users/verify',
  userData: BASEURL + 'users/profiles/me',
  countries: BASEURL + 'countries',
  updateIndUser: BASEURL + 'users/me/update-profile/individual',
  updateCorpUser: BASEURL + 'users/me/update-profile/corporate',
  updateUserNotificationStatus: BASEURL + 'users/attributes/notification',
  userChangePassword: BASEURL + 'users/me/update-password',
  businessDirectory: BASEURL + 'business-directories',
  getBusiness: BASEURL + 'business-directories/profiles/me',
  locations: BASEURL + 'locations',
  resetPassword: BASEURL + 'users/reset-password',
  contactRequest: BASEURL + 'contact-requests',
  getPublicBusiness: BASEURL + 'business-directories/',
  propertyCategory: BASEURL + 'properties/category/list',
  properties: BASEURL + 'properties',
  myProperties: BASEURL + 'properties/list/me',
  myProperty: BASEURL + 'properties/',
  vehicles: BASEURL + 'vehicles',
  vehicleCategory: BASEURL + 'vehicles/categories',
  products: BASEURL + 'products',
  bestDealProducts: BASEURL + 'products/best-deal',
  myProducts: BASEURL + 'products/list/me',
  productCategories: BASEURL + 'products/categories',
  productSubCategories: BASEURL + 'products/sub-categories/',
  productBrands: BASEURL + 'products/brands/',
  productSlug: BASEURL + 'products/slugs/',
  services: BASEURL + 'services',
  myServices: BASEURL + 'services/list/me',
  serviceCategories: BASEURL + 'services/categories',
  serviceSubCategories: BASEURL + 'services/sub-categories/',
  bestDealServices: BASEURL + 'services/best-deal',
  servicesSlug: BASEURL + 'services/slugs/',
  jobs: BASEURL + 'jobs',
  jobCategories: BASEURL + 'jobs/categories',
  jobSubCategories: BASEURL + 'jobs/sub-categories/',
  jobQualifications: BASEURL + 'jobs/qualifications',
  myJobs: BASEURL + 'jobs/list/me',
  jobsSlug: BASEURL + 'jobs/slugs/',
  jobApplications: BASEURL + 'jobs/applications/list',
  applyJobs: BASEURL + 'jobs/applications',
  userExist: BASEURL + 'users/check/',
  myFeeds: BASEURL + 'user-feeds/list/me',
  likeUserFeed: BASEURL + 'user-feeds/likes/',
  blockFeed: BASEURL + 'user-feeds/block-users',
  aroundMe: 'http://api.mycommunity.hashin.in/v1/around-me.json',
  myPromotions: BASEURL + 'promotions/',
  notification: BASEURL + '/notifications',
  users: BASEURL + 'users/',
  jobsUsers: BASEURL + 'jobs/user/',
  productsUsers: BASEURL + 'products/user/',
  propertiesUsers: BASEURL + 'properties/user/',
  vehiclesUsers: BASEURL + 'vehicles/user/',
  feedsUsers: BASEURL + 'user-feeds/user/',
  servicesUsers: BASEURL + 'services/user/',
  jobsPromoted: BASEURL + 'promote-list-slots/module/jobs',
  productsPromoted: BASEURL + 'promote-list-slots/module/products',
  propertiesPromoted: BASEURL + 'promote-list-slots/module/properties',
  vehiclesPromoted: BASEURL + 'promote-list-slots/module/vehicles',
  servicesPromoted: BASEURL + 'promote-list-slots/module/services',
  adsHome: BASEURL + 'ads/banner/pages/home',
  adsFeedHome: BASEURL + 'ads/feed/pages/home',
  moduleTypes: BASEURL + 'promote-list-slots/module-types',
  slots: BASEURL + 'promote-list-slots/time-slots',
  refreshSlots: BASEURL + 'refresh-list/time-slots',
  jobItems: BASEURL + 'jobs/list/me',
  propertiesItems: BASEURL + 'properties/list/me',
  promotionItems: BASEURL + 'promotions',
  vehicleItems: BASEURL + 'vehicles/list/me',
  productsItems: BASEURL + 'products/list/me',
  servicesItems: BASEURL + 'services/list/me',
  checkSlot: BASEURL + 'promote-list-slots/check-slot-availablity',
  bookPromotionSlot: BASEURL + 'promote-list-slots',
  adsList: BASEURL + 'ads/list/me',
  myDealsPromoted: BASEURL + 'promote-list-slots/module/deals',
  homeMyDeals: BASEURL + 'promotions/public/list?limit=8',
  myDeals: BASEURL + 'promotions/public/list',
  myDealDetails: BASEURL + 'promotions/',
  myDealsCategories: BASEURL + 'promotions/categories',

  malls: BASEURL + 'malls',
  mallDetails: BASEURL + 'malls/slugs/',
  news: BASEURL + 'news-articles',
  newsDetails: BASEURL + 'news-articles/slugs/',
  headings: BASEURL + 'news-articles/headings/',

  cvList: BASEURL + 'jobs/applications/list/',
  defaultAds: BASEURL + 'floating-ads?limit=3',

  shopsInMall: BASEURL + 'shops?mallId=',
  shopDetails: BASEURL + 'shops/slugs/',
  categories: BASEURL + 'search/categories',

  dashboardMyDeals: BASEURL + 'promotions',
  dashboardAddMyDeals: BASEURL + 'promotions',

  checkSlotForRefresh: BASEURL + 'refresh-list/check-slot-availablity',
  bookRefreshSlot: BASEURL + 'refresh-list',

  myDealsOtherProfile: BASEURL + 'promotions/public/list',
};
